name: Deploy API to Azure Web App

on:
  push:
    branches:
      - main  # Trigger deployment when code is pushed to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore TaskManagerAPI/TaskManagerAPI.sln

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Publish
      run: dotnet publish -c Release -o ${{ github.workspace }}/publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: taskmanager-api
        package: ${{ github.workspace }}/publish
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
