name: Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            api:
              - 'TaskManagerAPI/**'
            frontend:
              - 'TaskManagerFrontEnd/**'

  deploy_api:
    needs: detect_changes
    if: needs.detect_changes.outputs.api_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build API
        run: dotnet build --configuration Release

      - name: Publish API
        run: dotnet publish -c Release -o api_output

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TaskManagerAPI'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: api_output

  deploy_frontend:
    needs: detect_changes
    if: needs.detect_changes.outputs.frontend_changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: TaskManagerFrontEnd
        run: npm install

      - name: Build Frontend
        working-directory: TaskManagerFrontEnd
        run: npm run build

      - name: Deploy to Azure Static Web Apps
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          app_location: 'TaskManagerFrontEnd'
          output_location: 'TaskManagerFrontEnd/dist/task-manager-frontend'
