name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build API
        working-directory: TaskManagerAPI
        run: dotnet build --configuration Release

      - name: Publish API
        working-directory: TaskManagerAPI
        run: dotnet publish -c Release -o api_output

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TaskManagerAPI'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: TaskManagerAPI/api_output

  deploy_frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: TaskManagerFrontEnd
        run: npm install

      - name: Build Frontend
        working-directory: TaskManagerFrontEnd
        run: npm run build -- --configuration=production

      - name: Ensure deployment directory exists
        run: mkdir -p TaskManagerFrontEnd/dist/wwwroot

      - name: Move Angular build files
        run: mv -f TaskManagerFrontEnd/dist/task-manager-frontend/browser TaskManagerFrontEnd/dist/wwwroot/

      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TaskManagerFrontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: TaskManagerFrontEnd/dist/wwwroot
