name: Deploy to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch: 

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      api_changed: ${{ steps.filter.outputs.api }}
      frontend_changed: ${{ steps.filter.outputs.frontend }}
      force_deploy: ${{ github.event_name == 'workflow_dispatch' }} 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Detect changes
        id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            api:
              - 'TaskManagerAPI/**'
            frontend:
              - 'TaskManagerFrontEnd/**'

  deploy_api:
    needs: detect_changes
    if: needs.detect_changes.outputs.api_changed == 'true' || needs.detect_changes.outputs.force_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0'

      - name: Build API
        run: dotnet build --configuration Release

      - name: Publish API
        run: dotnet publish -c Release -o api_output

      - name: Deploy API to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TaskManagerAPI'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: api_output

  deploy_frontend:
    needs: detect_changes
    if: needs.detect_changes.outputs.frontend_changed == 'true' || needs.detect_changes.outputs.force_deploy == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install dependencies
        working-directory: TaskManagerFrontEnd
        run: npm install

      - name: Build Frontend
        working-directory: TaskManagerFrontEnd
        run: npm run build --prod

      - name: Deploy Frontend to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'TaskManagerFrontend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE_FRONTEND }}
          package: TaskManagerFrontEnd/dist/task-manager-frontend
